name: 'build'
on: ['push', 'pull_request']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: |
          yarn install
          yarn run build --prod --output ../server/public
        working-directory: './server'
      - run: |
          yarn install
          yarn run build:prod
        working-directory: './web'