name: 'build'
on: ['push', 'pull_request']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: cd web
      - run: yarn install
      - run: yarn run build --prod --output ../server/public
      - run: cd ../server
      - run: yarn install
      - run: yarn run build:prod